import { db } from "./src/index";
import { blogPostsTable } from "./src/schema/blog";

const BLOG_POSTS = [
  {
    slug: "what-is-personal-resilience",
    title: "What Is Personal Resilience — and Why Measuring It Changes Everything",
    description: "Personal resilience is more than just 'bouncing back'. Discover the six dimensions that determine how well you'll handle adversity — and why scoring yourself is the first step to real preparedness.",
    pillar: "assessment",
    pillarLabel: "Resilience Assessment",
    targetKeyword: "personal resilience",
    publishedAt: new Date("2026-05-01"),
    readingTimeMin: 6,
    body: [
      "Most people think resilience is a personality trait — something you either have or you don't. The research says otherwise.",
      "Decades of academic work on resilience, from the Connor-Davidson Resilience Scale to FEMA's Individual Preparedness Framework, all point to the same conclusion: resilience is measurable, multidimensional, and buildable. You don't need to be born tough. You need to be *prepared*.",
      "## The Six Dimensions That Actually Matter",
      "Resilium measures resilience across six domains that together predict how well you'd weather a serious disruption — a job loss, a health crisis, a natural disaster, or any of the life events that feel unlikely right until they're not.",
      "**Financial resilience** is the most immediately impactful: how many months of living expenses could you cover if income stopped today? Most Americans are one or two paychecks from crisis. Knowing your number is the beginning of changing it.",
      "**Skills resilience** measures the portability and demand of what you can do. In an economy where entire job categories are being automated, the question isn't just whether you're employed — it's whether your skills would still pay the bills if your industry collapsed.",
      "**Health resilience** covers both your current medical situation and how it would affect your options in a crisis. Medical debt is the leading cause of personal bankruptcy in the US. This dimension isn't about being healthy; it's about understanding your medical risk surface.",
      "**Geographic resilience** is the dimension most people never consider. Where you live determines your natural disaster risk, your access to support networks, and how easily you could relocate if necessary. Location is a preparedness variable.",
      "**Psychological resilience** draws on validated clinical scales like the Connor-Davidson to assess how you handle stress, uncertainty, and adversity. Mental clarity under pressure determines how well all your other preparations actually get used.",
      "**Resources and community** measures your social capital: the people and systems that would show up if things went wrong. Research consistently shows that community connections are as protective as financial resources — often more so.",
      "## Why Scoring Matters",
      "The problem with most preparedness advice is that it's generic. 'Save six months of expenses' is good advice in the abstract, but it ignores your specific situation. Someone with deep family support and portable skills needs a different plan than someone who's self-employed, geographically isolated, and managing a chronic health condition.",
      "A scored assessment changes that. When you see that your financial resilience score is 34/100 but your psychological resilience is 78/100, you know *exactly* where to focus. You stop guessing and start planning.",
      "## The Research Behind the Score",
      "Resilium's assessment methodology draws on peer-reviewed academic work including the Connor-Davidson Resilience Scale (Connor & Davidson, 2003), the Brief Resilience Scale (Smith et al., 2008), Antonovsky's Sense of Coherence theory, and FEMA's Individual and Household Preparedness Framework.",
      "## What a Good Score Looks Like",
      "A composite resilience score above 70 indicates strong preparedness across most dimensions. Scores between 40 and 70 reflect typical levels. Scores below 40 in any single dimension represent meaningful gaps that deserve immediate attention.",
    ],
    status: "published",
  },
  {
    slug: "financial-resilience-explained",
    title: "Financial Resilience Explained: The One Number Your Advisor Never Tells You",
    description: "Your net worth doesn't measure your financial resilience. The metric that matters in a crisis is runway — and most people have far less than they think.",
    pillar: "dimensions",
    pillarLabel: "Dimension Deep-Dive",
    targetKeyword: "financial resilience",
    publishedAt: new Date("2026-05-02"),
    readingTimeMin: 8,
    body: [
      "Financial advisors talk about net worth, investment allocation, and retirement projections. But in a crisis, the metric that matters is *runway*: how many months you could survive without income.",
      "## Runway Is Not the Same as Savings",
      "A $400,000 retirement account with a 10% early withdrawal penalty and a three-week processing time is nearly inaccessible in a real crisis. Runway is accessible cash divided by your real monthly expenses.",
      "## What the Research Says",
      "The Federal Reserve's Survey of Consumer Finances consistently finds that roughly 40% of American adults cannot cover a $400 unexpected expense without borrowing. Income isn't the constraint — lifestyle inflation and the absence of liquid reserves are.",
      "## The Five Factors Resilium Measures",
      "**Emergency runway** — months of accessible living expenses. Three months is the minimum. Six months is the target.",
      "**Income diversity** — how many streams of income you have. A single employer is a single point of failure.",
      "**Debt burden** — how quickly your debt obligations would become unmanageable without income.",
      "**Insurance coverage** — health, disability, and property insurance are financial resilience tools.",
      "**Financial flexibility** — access to credit, the ability to reduce expenses quickly, and the existence of a financial plan.",
    ],
    status: "published",
  },
  {
    slug: "job-loss-emergency-plan",
    title: "Job Loss Emergency Plan: What to Do in the First 7 Days",
    description: "Losing a job is disorienting. Having a plan eliminates the paralysis. Here's the exact sequence of actions that protect your financial resilience in the first week.",
    pillar: "scenarios",
    pillarLabel: "Scenario Planning",
    targetKeyword: "job loss financial plan",
    publishedAt: new Date("2026-05-03"),
    readingTimeMin: 7,
    body: [
      "Job loss is one of the most common financial crises a person faces. The people who navigate it best almost always made key decisions before it happened.",
      "## Day 1: Stabilize",
      "Calculate your runway. How much cash can you access right now? What are your fixed monthly obligations? That ratio is your reality.",
      "## Day 2–3: Benefits and Claims",
      "File for unemployment immediately. Review COBRA options — you typically have 60 days but paperwork takes time.",
      "## Day 4–5: Reduce Your Burn Rate",
      "List every recurring expense. Cancel discretionary items. Call landlords and creditors — most have hardship programs that aren't advertised.",
      "## Day 6–7: Income and Timeline",
      "Write out a realistic job search timeline. In most professional fields, expect 8–16 weeks. Tell people in your network you're looking. Most jobs are filled through networks, not applications.",
      "## The Psychological Piece",
      "A written plan is the best counter-measure to decision-impairment from financial stress. Once you've made and written down the key decisions, you stop holding them in working memory.",
    ],
    status: "published",
  },
  {
    slug: "6-dimensions-of-personal-resilience",
    title: "The 6 Dimensions of Personal Resilience (and How to Score Them)",
    description: "Resilience isn't one thing — it's six. Understanding each dimension shows you exactly where you're strong, where you're vulnerable, and what to do about it.",
    pillar: "assessment",
    pillarLabel: "Resilience Assessment",
    targetKeyword: "resilience dimensions",
    publishedAt: new Date("2026-05-07"),
    readingTimeMin: 9,
    body: [
      "Resilience is a six-factor model: distinct domains of preparedness that can be measured and improved independently.",
      "## Dimension 1: Financial Resilience",
      "Measures your ability to sustain yourself economically when income stops. Core metric: runway — months of accessible living expenses.",
      "## Dimension 2: Skills Resilience",
      "How economically portable and future-proof your professional capabilities are. If your industry collapsed, how quickly could you generate income?",
      "## Dimension 3: Health Resilience",
      "How would your current health affect your ability to work in a crisis, and how financially exposed are you to medical costs?",
      "## Dimension 4: Geographic Resilience",
      "Where you live determines your natural disaster exposure, cost of living, access to infrastructure, and ability to relocate.",
      "## Dimension 5: Psychological Resilience",
      "Draws on the Connor-Davidson Resilience Scale. Measures stress tolerance, adaptability, sense of control, and social connection.",
      "## Dimension 6: Resources and Community",
      "Your social capital — the people and community systems that would support you in a crisis. Research shows community connections are as protective as financial resources.",
      "## Reading Your Profile",
      "A balanced score across all six dimensions is better than a high average driven by one strong area. Your lowest-scoring dimension is almost always the right place to start.",
    ],
    status: "published",
  },
  {
    slug: "psychological-resilience-10-questions",
    title: "Psychological Resilience: The 10 Questions That Reveal How You'll Handle Adversity",
    description: "Validated clinical scales distilled into a clear framework. These are the questions that predict how you'll perform under pressure — and what you can do to improve your score.",
    pillar: "dimensions",
    pillarLabel: "Dimension Deep-Dive",
    targetKeyword: "psychological resilience",
    publishedAt: new Date("2026-05-08"),
    readingTimeMin: 7,
    body: [
      "The Connor-Davidson Resilience Scale demonstrates that psychological resilience is both measurable and improvable. It's not a fixed personality trait.",
      "## The Five Factors",
      "**Stress tolerance** — maintaining performance and decision quality when pressure is high.",
      "**Adaptability** — adjusting plans when circumstances change unexpectedly.",
      "**Personal competence** — belief in your ability to handle challenges (related to self-efficacy research).",
      "**Sense of control** — whether you see your situation as something you can influence. One of the most robust predictors of resilience outcomes.",
      "**Social connection** — whether you draw strength from relationships. Social support is a documented stress buffer.",
      "## Ten Questions to Ask Yourself",
      "1. When something unexpected disrupts your plans, how quickly do you typically recover?",
      "2. When facing a difficult problem, do you generally believe you'll find a solution?",
      "3. Can you identify at least three people who would actively support you through a personal crisis?",
      "4. When stressed, does your decision-making quality improve, stay the same, or worsen significantly?",
      "5. Have you experienced significant adversity before and come through it?",
      "6. Do you believe your actions meaningfully affect your outcomes?",
      "7. Can you continue functioning in daily life while carrying significant stress?",
      "8. Do you have regular practices (sleep, exercise, reflection) that maintain your baseline mental state?",
      "9. When circumstances change, can you update your plans without prolonged distress?",
      "10. Do the people close to you describe you as steady under pressure?",
      "## Improving Psychological Resilience",
      "Exposure to manageable adversity builds stress tolerance. Reflective practices build self-awareness. Physical health maintenance sustains stress tolerance. Sense of control improves through action.",
    ],
    status: "published",
  },
  {
    slug: "10-documents-you-need-before-crisis",
    title: "The 10 Documents You Need to Have Ready Before a Crisis",
    description: "When an emergency happens, you don't have time to find your insurance policy. These are the documents that matter most — and how to organize them so they're actually available when you need them.",
    pillar: "how-to",
    pillarLabel: "How-To Guide",
    targetKeyword: "emergency document checklist",
    publishedAt: new Date("2026-05-09"),
    readingTimeMin: 6,
    body: [
      "Document preparedness is one of the lowest-effort, highest-impact resilience investments available. It takes two or three hours once and saves enormous stress when it matters most.",
      "## The 10 Documents That Matter Most",
      "**1. Government-issued ID (multiple copies).** Passport, driver's license, or state ID. A digital photo in secure cloud storage is a meaningful backup.",
      "**2. Health insurance card and policy details.** Know your deductible, out-of-pocket maximum, and which hospitals are in-network.",
      "**3. Homeowner's or renter's insurance policy.** Read yours. Know what it covers, what it doesn't, and how to file a claim before you need to.",
      "**4. Auto insurance policy.** Know your coverage, deductible, and insurer's emergency claims line.",
      "**5. Bank account information.** Account numbers, routing numbers, and direct contact for your bank. In a disaster, ATMs fail.",
      "**6. Employment records.** Most recent pay stubs, offer letter, and HR contact. Needed for unemployment claims and loan applications.",
      "**7. Medical records and medication list.** Diagnoses, current medications with dosages, and primary care contact.",
      "**8. Estate planning documents.** Will, power of attorney, healthcare proxy. If you're incapacitated, someone needs legal authority to make decisions.",
      "**9. Tax returns (last 2 years).** Required for loan applications, government assistance, and rental applications.",
      "**10. Emergency contacts list.** Physical, printed — not just in your phone. Include someone out of state.",
      "## How to Organize Them",
      "Use a waterproof physical folder plus a secure digital backup. Review and update the folder once a year — a calendar reminder on your birthday works well.",
    ],
    status: "published",
  },
  {
    slug: "what-happens-if-you-lose-your-job-tomorrow",
    title: "What Happens to Your Finances If You Lose Your Job Tomorrow?",
    description: "Most people have never run the numbers. Walk through a realistic scenario analysis — and find out whether your financial resilience score matches what you think it is.",
    pillar: "scenarios",
    pillarLabel: "Scenario Planning",
    targetKeyword: "job loss scenario",
    publishedAt: new Date("2026-05-13"),
    readingTimeMin: 8,
    body: [
      "Imagine it's a Tuesday. You get a message from your manager asking for a call. By noon, you're no longer employed. What happens to your finances?",
      "## The First 30 Days",
      "In the first month, the impact is mostly about cash flow. If you have three months of liquid reserves, you have time to be deliberate. If you have less than one month — true for roughly 40% of American workers — immediate action is required.",
      "## The 60–90 Day Window",
      "Most professional job searches take 8–16 weeks. Unemployment benefits replace roughly 40–60% of previous income. For someone earning $80,000/year, the monthly deficit can be $1,500–$2,300 — adding up to $4,500–$6,900 over a 12-week search.",
      "## The Scenario Analysis",
      "Your break-even date — when reserves run out — is the number that matters. If it's more than six months away, you're financially resilient for a typical job loss scenario. If it's less than three months away, urgency is appropriate.",
      "## What High-Resilience Looks Like",
      "People with high financial resilience scores show three patterns: at least six months of accessible reserves, at least one additional income stream, and flexible expenses that can be meaningfully reduced without touching essential obligations.",
      "## The Planning Use Case",
      "Running this scenario when your employment is stable is the most valuable time — because you can actually act on what you find.",
    ],
    status: "published",
  },
  {
    slug: "geographic-resilience-where-you-live",
    title: "Geographic Resilience: Why Where You Live Is a Risk Variable, Not a Given",
    description: "Your address determines more of your resilience profile than most people realize. Here's how to think about location as a preparedness variable — and what you can do about it.",
    pillar: "dimensions",
    pillarLabel: "Dimension Deep-Dive",
    targetKeyword: "geographic resilience",
    publishedAt: new Date("2026-05-14"),
    readingTimeMin: 6,
    body: [
      "Where you live determines your natural disaster exposure, cost of living, access to healthcare, and critically — how easily you could leave if you needed to.",
      "## The Risk Dimensions of Location",
      "**Natural disaster exposure** — FEMA's National Risk Index provides publicly available data on disaster risk by county. Do you have adequate insurance and a documented evacuation plan?",
      "**Local economic resilience** — single-industry towns and regions with concentrated employment are structurally less resilient for residents.",
      "**Healthcare access** — in rural areas, the nearest hospital may be 40 minutes away. For anyone managing a chronic condition, proximity to specialists is a genuine resilience factor.",
      "**Mobility** — do you own or rent? Do you have family or friends in other cities? Could you fund a relocation on short notice?",
      "## What You Can Do",
      "Geographic resilience doesn't necessarily mean moving. Understand your specific location risks using FEMA's NRI tool. Purchase insurance appropriate to your location. Build a documented evacuation plan if you're in a high-risk area.",
      "If relocation is genuinely an option you're considering, run the scenario explicitly. Where would you go? What would it cost? What would you gain in resilience terms?",
    ],
    status: "published",
  },
  {
    slug: "how-to-build-3-month-emergency-fund",
    title: "How to Build a 3-Month Emergency Fund (Even If You're Barely Saving Now)",
    description: "Three months of accessible reserves is the most impactful financial resilience goal most people can achieve. Here's a practical framework that works even on a tight budget.",
    pillar: "how-to",
    pillarLabel: "How-To Guide",
    targetKeyword: "how to build emergency fund",
    publishedAt: new Date("2026-05-15"),
    readingTimeMin: 7,
    body: [
      "A three-month emergency fund is achievable on nearly any stable income — and it's the single most impactful financial resilience investment most people can make.",
      "## Step 1: Calculate Your Real Monthly Expenses",
      "The three-month target is three months of actual monthly expenses, not income. List every monthly outflow: rent, utilities, groceries, transportation, insurance, minimum debt payments, personal spending. Add them up.",
      "## Step 2: Find the Gap",
      "Subtract your current accessible reserves from your three-month target. If your monthly expenses are $3,200 and you have $1,800 in savings, your target is $9,600 and your gap is $7,800.",
      "## Step 3: Build the System",
      "Automate contributions and treat the fund as non-negotiable. Set up an automatic transfer to a separate high-yield savings account on the day your paycheck arrives. Separate accounts matter — money in checking gets spent.",
      "## Step 4: Accelerate Where Possible",
      "One-time windfalls — tax refunds, bonuses — are disproportionately powerful. A $2,500 tax refund directed entirely to the fund closes 32% of a $7,800 gap immediately.",
      "## The Psychological Payoff",
      "An emergency fund breaks the cycle of financial stress impairing the decision-making quality that would reduce it. Most people who build a three-month fund report it as one of the highest-confidence financial decisions they've made.",
    ],
    status: "published",
  },
  {
    slug: "good-resilience-score-interpretation",
    title: "What's a Good Resilience Score? Here's How to Interpret Yours",
    description: "A number without context isn't useful. Here's how Resilium scores are structured, what different score ranges mean, and how to use your result to prioritize your next steps.",
    pillar: "assessment",
    pillarLabel: "Resilience Assessment",
    targetKeyword: "good resilience score",
    publishedAt: new Date("2026-05-20"),
    readingTimeMin: 5,
    body: [
      "Getting a resilience score is the beginning of the process, not the end. The number matters — but what matters more is what you do with it.",
      "## How the Score Is Structured",
      "The Resilium score is a composite of six dimension scores, each measured on a 0–100 scale, weighted to reflect relative impact on overall preparedness.",
      "## Score Ranges",
      "**70–100: Strong resilience.** Meaningful preparedness across most dimensions. Focus is on optimization rather than gap-filling.",
      "**50–69: Moderate resilience.** The most common range. Real strengths in some dimensions and meaningful gaps in others.",
      "**30–49: Below-average resilience.** Multiple dimensions with significant vulnerabilities. Start a prioritized plan with the lowest-scoring dimension.",
      "**Under 30: High vulnerability.** Uncommon but represents meaningful risk. Immediate, focused action on the highest-impact gap is recommended.",
      "## How to Use Your Dimension Breakdown",
      "Look for the dimension with your lowest score — that's where incremental effort produces the highest return in overall resilience.",
      "## What 'Good' Really Means",
      "A score of 70+ is a reasonable definition of 'good'. But 'better than yesterday' is more useful than 'above a threshold'. Use the score as a baseline and retake the assessment in six months to track progress.",
    ],
    status: "published",
  },
];

async function main() {
  console.log("Seeding blog posts…");
  let skipped = 0;
  let inserted = 0;
  for (const post of BLOG_POSTS) {
    try {
      await db.insert(blogPostsTable).values(post).onConflictDoNothing();
      console.log(`  ✓ ${post.slug}`);
      inserted++;
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      console.log(`  ⚠ ${post.slug} skipped: ${msg}`);
      skipped++;
    }
  }
  console.log(`Done. ${inserted} inserted, ${skipped} skipped.`);
  process.exit(0);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
