import React from "react";
import { Link } from "wouter";
import { SiteFooter } from "@/components/site-footer";
import { ResilientIcon } from "@/components/resilient-icon";

const LAST_UPDATED = "March 27, 2026";
const CONTACT_EMAIL = "contact_resilium@pm.me";

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <header className="w-full py-6 px-6 lg:px-12 border-b border-border/60">
        <Link href="/" className="flex items-center gap-2 w-fit">
          <ResilientIcon className="w-7 h-7" />
          <span className="font-display font-bold text-xl tracking-tight text-primary">Resilium</span>
        </Link>
      </header>

      <main className="flex-1 w-full max-w-3xl mx-auto px-6 py-12 space-y-10">
        <div>
          <h1 className="text-4xl font-display font-bold tracking-tight mb-3">Terms and Conditions</h1>
          <p className="text-sm text-muted-foreground">Last updated: {LAST_UPDATED}</p>
        </div>

        <p className="text-muted-foreground leading-relaxed">
          These Terms and Conditions govern your use of Resilium, a personal resilience planning platform. By accessing or using Resilium, you agree to these terms. Please read them carefully before using the service.
        </p>

        <Section title="1. About the Service">
          <p>
            Resilium is an independent platform that provides personalized resilience scoring, risk analysis, and action planning using self-reported data and AI-generated insights. The service is operated by a sole individual.
          </p>
          <p>
            Resilium is an informational and self-improvement tool only. Nothing on this platform constitutes professional financial, medical, legal, psychological, or emergency management advice. You are responsible for your own decisions and actions based on the information provided.
          </p>
        </Section>

        <Section title="2. Eligibility">
          <p>
            You must be at least 16 years of age to use Resilium. By using the service, you confirm that you meet this requirement. Resilium is not intended for use by minors under the age of 16.
          </p>
        </Section>

        <Section title="3. User Accounts">
          <p>
            Creating an account allows you to save your assessments, track progress over time, and access all features appropriate to your plan. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account.
          </p>
          <p>
            You agree not to use the platform for any unlawful purpose, to misrepresent your identity, or to attempt to reverse-engineer, scrape, or disrupt the service.
          </p>
        </Section>

        <Section title="4. Subscriptions and Billing">
          <p>
            Resilium offers a free Starter plan and a paid Pro subscription. Subscriptions are billed through Paddle, our authorised payment processor. By subscribing, you agree to Paddle's terms of service and authorise recurring charges to your chosen payment method at the applicable rate.
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li><strong>Monthly plans</strong> are billed every 30 days from the subscription start date.</li>
            <li><strong>Annual plans</strong> are billed once per year from the subscription start date.</li>
            <li>Prices are displayed inclusive or exclusive of applicable taxes depending on your jurisdiction, as determined at checkout.</li>
            <li>You may cancel your subscription at any time. Cancellation takes effect at the end of the current billing period — you will retain Pro access until then.</li>
          </ul>
          <p>
            Resilium reserves the right to change pricing. Any price changes will be communicated to you in advance and will take effect at the start of your next billing cycle.
          </p>
        </Section>

        <Section title="5. Refunds">
          <p>
            Please refer to our{" "}
            <Link href="/refund" className="text-primary underline underline-offset-4 hover:text-primary/80">
              Refund Policy
            </Link>
            {" "}for full details. In summary, refund requests are handled on a case-by-case basis and must be submitted within 14 days of purchase.
          </p>
        </Section>

        <Section title="6. AI-Generated Content">
          <p>
            Your resilience report, action plan, and scenario analysis are generated by artificial intelligence based on your self-reported inputs. AI-generated content may contain errors, omissions, or inaccuracies. Resilium makes no guarantee as to the completeness, accuracy, or fitness for any particular purpose of AI-generated outputs.
          </p>
          <p>
            You should exercise your own judgment before acting on any AI-generated recommendation. Resilium is not liable for decisions or outcomes resulting from your use of AI-generated content.
          </p>
        </Section>

        <Section title="7. Intellectual Property">
          <p>
            All software, design, branding, and non-user-generated content on Resilium is the intellectual property of Resilium and its operator. You may not copy, distribute, reproduce, or create derivative works from the platform without explicit written permission.
          </p>
          <p>
            Your assessment data belongs to you. By submitting it, you grant Resilium a limited, non-exclusive licence to process and store that data for the purpose of providing the service, as described in our{" "}
            <Link href="/privacy" className="text-primary underline underline-offset-4 hover:text-primary/80">
              Privacy Policy
            </Link>
            .
          </p>
        </Section>

        <Section title="8. Limitation of Liability">
          <p>
            To the fullest extent permitted by applicable law, Resilium and its operator shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of or inability to use the service.
          </p>
          <p>
            Resilium's total liability to you for any claim arising out of or relating to these Terms shall not exceed the amount you paid for the service in the 12 months preceding the claim, or £100 (GBP), whichever is greater.
          </p>
        </Section>

        <Section title="9. Disclaimer of Warranties">
          <p>
            Resilium is provided "as is" and "as available" without warranties of any kind, either express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, or non-infringement. Resilium does not warrant that the service will be uninterrupted, error-free, or free of harmful components.
          </p>
        </Section>

        <Section title="10. Privacy">
          <p>
            Your use of Resilium is governed by our{" "}
            <Link href="/privacy" className="text-primary underline underline-offset-4 hover:text-primary/80">
              Privacy Policy
            </Link>
            , which is incorporated into these Terms by reference. By using Resilium, you consent to the collection and use of your data as described therein.
          </p>
        </Section>

        <Section title="11. Termination">
          <p>
            Resilium reserves the right to suspend or terminate your access to the service at any time, with or without notice, if you violate these Terms or engage in conduct that is harmful to the platform, its users, or its operator.
          </p>
          <p>
            You may delete your account at any time from your profile settings. Upon deletion, your personal data will be removed in accordance with our Privacy Policy.
          </p>
        </Section>

        <Section title="12. Changes to These Terms">
          <p>
            These Terms may be updated from time to time. The "Last updated" date at the top of this page will reflect any changes. For material changes, you will be notified via the platform or by email. Continued use of the service after changes constitutes your acceptance of the updated Terms.
          </p>
        </Section>

        <Section title="13. Governing Law">
          <p>
            These Terms are governed by and construed in accordance with the laws of England and Wales. Any disputes arising from these Terms shall be subject to the exclusive jurisdiction of the courts of England and Wales.
          </p>
        </Section>

        <div className="pt-4 border-t border-border/60">
          <p className="text-sm text-muted-foreground">
            Questions about these terms? Contact us at{" "}
            <a href={`mailto:${CONTACT_EMAIL}`} className="text-primary underline underline-offset-4 hover:text-primary/80">
              {CONTACT_EMAIL}
            </a>
          </p>
        </div>
      </main>

      <SiteFooter />
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="text-xl font-display font-bold">{title}</h2>
      <div className="space-y-3 text-foreground/80 leading-relaxed [&_strong]:text-foreground [&_strong]:font-semibold">
        {children}
      </div>
    </section>
  );
}
