kind = "web"
previewPath = "/"
title = "Resilium"
version = "1.0.0"
id = "artifacts/resilium"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19236

[services.development]
run = "pnpm --filter @workspace/resilium run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/resilium", "run", "build" ]
publicDir = "artifacts/resilium/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19236"
BASE_PATH = "/"
